language: python
python:
  - '2.7'
install: pip install -r requirements.txt --use-mirrors
services:
    - mongodb
script: make test
notifications:
  email:
    recipients:
      - allen@cobrain.com
      - ben@cobrain.com
      - sarah@cobrain.com
      - keshav@cobrain.com
    on_success: change
    on_failure: always
